### ISSUE TITLE
Github Action stopped working

### ISSUE THREAD

**Issue by joelleortiz** [moropo-com/action-trigger-test-run#49]
Hi, we're using the github action from the marketplace but it suddenly stopped working

![image](https://github.com/user-attachments/assets/8bce5681-de81-4b01-98af-a21ead2a4b2a)

We are using this in our yaml file:

```
      - name: Moropo - Trigger Mobile App Test Run
        uses: moropo-com/action-trigger-test-run@v2
        with:
          api_key: api key here
          scheduled_test_id: test id here
          sync: true
          env: 'env variables here'
```
